# Generated by Django 4.1.4 on 2022-12-26 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_alter_usermessage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='receiver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.usermessage'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
