# Generated by Django 4.1.4 on 2022-12-26 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_adminmessage_receiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='receiver',
            new_name='sender',
        ),
    ]
