# Generated by Django 4.2.1 on 2023-05-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0002_rename_timestamp_privatemessage_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='sender',
        ),
    ]
