# Generated by Django 4.2.1 on 2023-05-17 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MessageApp', '0003_remove_privatemessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='sender',
            field=models.ForeignKey(default=3, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
