# Generated by Django 4.2.1 on 2023-05-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0005_geeksmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
