# Generated by Django 4.2.1 on 2023-05-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0009_privatemessage_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='is_read',
        ),
    ]
